Ejjada/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ejjada.Models;

namespace Ejjada.Controllers
{
    public class AboutUsController : Controller
    {
        private EjjadaDb1 db = new EjjadaDb1();

        //
        // GET: /AboutUs/

        public ActionResult Index()
        {
            return View(db.Discriptions1.ToList());
        }

        //
        // GET: /AboutUs/Details/5

        public ActionResult Details(int id = 0)
        {
            AboutDiscript aboutdiscript = db.Discriptions1.Find(id);
            if (aboutdiscript == null)
            {
                return HttpNotFound();
            }
            return View(aboutdiscript);
        }

        //
        // GET: /AboutUs/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AboutUs/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AboutDiscript aboutdiscript)
        {
            if (ModelState.IsValid)
            {
                db.Discriptions1.Add(aboutdiscript);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aboutdiscript);
        }

        //
        // GET: /AboutUs/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AboutDiscript aboutdiscript = db.Discriptions1.Find(id);
            if (aboutdiscript == null)
            {
                return HttpNotFound();
            }
            return View(aboutdiscript);
        }

        //
        // POST: /AboutUs/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AboutDiscript aboutdiscript)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aboutdiscript).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aboutdiscript);
        }

        //
        // GET: /AboutUs/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AboutDiscript aboutdiscript = db.Discriptions1.Find(id);
            if (aboutdiscript == null)
            {
                return HttpNotFound();
            }
            return View(aboutdiscript);
        }

        //
        // POST: /AboutUs/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AboutDiscript aboutdiscript = db.Discriptions1.Find(id);
            db.Discriptions1.Remove(aboutdiscript);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Ejjada/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejjada.Controllers
{
    public class SuperAdminController : Controller
    {
        //
        // GET: /SuperAdmin/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Ejjada/Views/AboutUs/Create.cshtml
@model Ejjada.Models.AboutDiscript

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AboutDiscript</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Discription1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Discription1)
            @Html.ValidationMessageFor(model => model.Discription1)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ejjada/Views/AboutUs/Delete.cshtml
@model Ejjada.Models.AboutDiscript

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>AboutDiscript</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Discription1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Discription1)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Ejjada/Views/AboutUs/Details.cshtml
@model Ejjada.Models.AboutDiscript

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>AboutDiscript</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Discription1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Discription1)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ejjada/Views/AboutUs/Edit.cshtml
@model Ejjada.Models.AboutDiscript

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AboutDiscript</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Discription1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Discription1)
            @Html.ValidationMessageFor(model => model.Discription1)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ejjada/Views/AboutUs/Index.cshtml
@model IEnumerable<Ejjada.Models.AboutDiscript>

@{
    ViewBag.Title = "Index";
}
<h3>&nbsp;</h3>
<h2 class="container">(About Us)</h2>
<h3>&nbsp;</h3>
<p>
    <h3 class="btn btn-block btn-primary">
        @Html.ActionLink("Create New", "Create")
    </h3>
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Discription1)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Discription1)
                <h3>&nbsp;</h3>
            </td>
            <td class="btn btn-primary">
                |   @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |<h3>&nbsp;</h3>
                |  @Html.ActionLink("Details", "Details", new { id = item.Id }) |<h3>&nbsp;</h3>
                |  @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |<h3>&nbsp;</h3>
            </td>
        </tr>
    }

</table>
<div>
    <h3 class="btn btn-block btn-primary">
        @Html.ActionLink("Back", "Index", "SuperAdmin")
    </h3>
</div>